# Generated by Django 3.0.8 on 2020-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='approximation_total_interval',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='Total Approximation Interval'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='check_after_hours',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Check After Hours'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='minimum_moisture_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Moisture Level'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='sprinkler_port',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Sprinkler Port'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='state',
            field=models.BooleanField(blank=True, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='time_after_which_shutdown',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Time After Which Shutdown'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='type',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Type of action'),
        ),
    ]
