# Generated by Django 3.0.8 on 2020-07-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SprinklerData',
            fields=[
                ('time', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Time')),
                ('status_of_sprinkler', models.BooleanField(default=False, editable=False, verbose_name='Status of the Sprinkler')),
                ('approximation_total_interval', models.IntegerField(editable=False, verbose_name='Total Approximation Interval')),
                ('last_on', models.IntegerField(editable=False, verbose_name='Last Time On')),
                ('moisture_reading', models.FloatField(editable=False, verbose_name=' Moisture Reading')),
                ('was_close_overtime', models.BooleanField(default=False, editable=False, verbose_name='Was Sprinkler closed because of overtime.')),
                ('minimum_moisture_level', models.IntegerField(editable=False, verbose_name='Minimum Moisture Level')),
                ('time_after_which_shutdown', models.IntegerField(editable=False, verbose_name='Time after which to Shutdown')),
                ('check_after_hours', models.IntegerField(editable=False, verbose_name='Check after hours')),
                ('on_since', models.IntegerField(editable=False, verbose_name=' On since')),
            ],
        ),
    ]
