# Generated by Django 3.0.8 on 2020-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200703_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinklerdata',
            name='sprinkler_port',
            field=models.IntegerField(default=0, editable=False, verbose_name='Sprinkler Port'),
        ),
    ]
