# Generated by Django 3.0.8 on 2020-07-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_sprinklerdata_sprinkler_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprinklerdata',
            old_name='was_close_overtime',
            new_name='was_closed_overtime',
        ),
    ]
